// <auto-generated />
using System;
using DotaGrid.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotaGrid.DataAccess.Maintenance.Migrations
{
    [DbContext(typeof(HeroContext))]
    [Migration("20210521180619_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotaGrid.model.Hero", b =>
                {
                    b.Property<int>("HeroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<string>("E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<int?>("MainattributeId")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<int>("Ms")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Playstyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Q")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ultimate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("W")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HeroId");

                    b.HasIndex("MainattributeId");

                    b.ToTable("Hero");
                });

            modelBuilder.Entity("DotaGrid.model.Mainattribute", b =>
                {
                    b.Property<int>("MainattributeId")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MainAttributeType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MainattributeId");

                    b.ToTable("MainAttributes");
                });

            modelBuilder.Entity("DotaGrid.model.Hero", b =>
                {
                    b.HasOne("DotaGrid.model.Mainattribute", "Mainattribute")
                        .WithMany("Heroes")
                        .HasForeignKey("MainattributeId");
                });
#pragma warning restore 612, 618
        }
    }
}
